# Generated by Django 4.2.6 on 2023-10-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
    ]
